### ISSUE TITLE
关于一些博文的建议

### ISSUE THREAD

**Issue by iamCristYe** [wetxz/blog.github.io#1]
Hi!
搜索Windows自带Hash运算的时候搜索到了[您的这篇博文](http://blog.tangxiaozhu.com/p/7785bdeb/)，感觉非常有帮助。然后又忍不住读了一下其它文章，感觉很多内容都很有价值。非常感谢您的分享！
不过也有几篇文章想给您提点建议。因为您博客和知乎都没有可以留言的地方，就在这里给您留言啦：

1. 计算[Hash的这篇文章](http://blog.tangxiaozhu.com/p/7785bdeb/)中提到的FCIV这个命令还需要单独安装工具，建议使用`certutil -hashfile eg.ext SHA1`或`Get-FileHash eg.ext -Algorithm SHA1`（后者需PowerShell）

2. 这篇[去除This PC中文件夹的文章](http://blog.tangxiaozhu.com/p/65466aa3/)也十分实用。但其中提及

> WIN 8.1
> 同样适用于旧版本 WIN 10

与

> WIN 10

似乎会让人感到混淆，建议改为`Windows 10 1507 及之前`与`Windows 10 1511 及之后`。其中第二部分的分享已经失效，建议删去或传上GitHub后更新链接。方法二中的注册表路径用了全角的`＼`而不是半角的`\`，不便访问，希望修改。

3. [有关按需安装Office 365的这篇文章](http://blog.tangxiaozhu.com/p/d431df38/)中提及的XML微软提供了一个[官方工具](http://officedev.github.io/Office-IT-Pro-Deployment-Scripts/XmlEditor.html)，可以考虑介绍。

另外还有一点疑问……您这个博客应该也是基于Hexo搭建的吧？我之前也想这么搞，但发现放上GitHub的只是生成的Blog文件，源文件还需要自己另外备份？请问您是怎么处理的？
再次感谢您的精彩原创内容！

**Comment by wetxz** [comment]
谢了：
1. 已添加相应内容，但是我使用的时候不需要单独安装……
2. 已修改；
3. 这个官方工具没法设置只安装 Office 三套件啊；
4. 是 Hero 搭建的，在关于页面有说明。源文件使用 Dropbox 备份的，也有人写了 Hexo Backup 可以备份到 GitHub，但我没用哟；

5. 访问我的博客，你的电脑风扇有转么？自从加了动态背景后，我用 MacBook Pro 访问博客风扇会转起来，在活动监视器里发现其占用内存较高，但是系统空闲内存还有 80% 左右，所以一直很纳闷……

**Comment by iamCristYe** [comment]
@wetxz 

1. 那个应该是要装 https://www.microsoft.com/en-us/download/details.aspx?id=11533 这个的呀……可能你的系统不是原版？
2. Office 那个左边有个Exclude Programs里面可以选
3. Hexo 那点谢啦！不过感觉自己水平还是先不用了
4. Surface Pro 3 ＋ Chrome 没转……不过好像你已经把动态背景去掉了？

**Comment by tjuzl** [comment]
@iamCristYe 
1. 可能是我忘记了…… 但系统是在虚拟机中运行的原版正版 Windows 10；
2. 排除以后然后选择 `Download Office Deployment Tool`，是么？
4. 是的，去掉了，电脑风扇就不转了…… 之前在 Safari 与 Chrome 打开都出现这问题。

**Comment by iamCristYe** [comment]
@wetxz 
是的，那个工具只是原来帮助你写Office Deployment Tool要用到的XML文件。

**Comment by wetxz** [comment]
@iamCristYe 
可能是我忘记了…… 但系统是在虚拟机中运行的原版正版 Windows 10；
排除以后然后选择 Download Office Deployment Tool，是么？
是的，去掉了，电脑风扇就不转了…… 之前在 Safari 与 Chrome 打开都出现这问题。

@wetxz
是的，那个工具只是原来帮助你写Office Deployment Tool要用到的XML文件。

@iamCristYe 
用错浏览器了，那个号是不用的，刚刚删除了……

另外，我 Exclude 了部分应用，下载选项只出现了 `officedeploymenttool_8008-3601.exe`，
而没有 `configuration.xml`，这是确认可行的么？因为我不用 Windows 了，无法确认。

**Comment by iamCristYe** [comment]
@wetxz 
没有问题呀，你设置完点那个Export就好了。Deployment Tool还是要去官网下，那个只是个生成XML的文件。我就是用这个装的。

**Comment by wetxz** [comment]
你看下我点 `save` 以后，还是空白…… 什么情况？

Chrome 
<img width="1062" alt="2017-06-10 01 48 16" src="https://user-images.githubusercontent.com/9845703/26987639-ec4e772a-4d7e-11e7-9d11-c93db58afc3c.png">

**Comment by iamCristYe** [comment]
你是要先在第一个界面里选好版本点Add Product
![image](https://user-images.githubusercontent.com/12642018/26988107-deab18a2-4d02-11e7-9f87-99d35776906f.png)
然后再去第二个页面Save
![image](https://user-images.githubusercontent.com/12642018/26988125-ee83fece-4d02-11e7-9dfc-4568a0be3ddd.png)
最后点Export

**Comment by wetxz** [comment]
@iamCristYe 
了解～ Nice.
